### ISSUE TITLE
Golang 

### ISSUE THREAD

**Issue by gedw99** [ashtonmeuser/godot-wasm#55]
I Write in golang and it would be awesome if golsng worked ..

Btw I use Wazero as a wasm runner.
 Wazero is Portable to anything. Servers, desktops and mobiles. Just mentioning this as it might be useful to this project. It’s written in golang itself.

**Comment by Trey2k** [comment]
Is there a reason golang would not currently work?

**Comment by ashtonmeuser** [comment]
Hey @gedw99 thanks for the suggestion. I see a few improvements to Godot Wasm that could help with Golang fans (I include myself in this group). I'm going to include some context here for posterity.

Technically, any language targeting Wasm is supported by this project. That said, typically, compiling Golang to a Wasm module actually targets [WASI](https://wasi.dev/). There is currently no Go equivalent of Rust's [`wasm32-unknown-unknown`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_target/spec/wasm32_unknown_unknown/index.html) target. Despite this, Godot Wasm should support modules built for WASI although there may be a few hoops to jump through.

A simple Go program compiled to Wasm via TinyGo (`tinygo build -o tinygo.wasm -target wasi main.go`) produces a Wasm module with the following signature.

```
Type: wasm
Size: 68.6 KB
Imports:
  Functions:
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
  Memories:
  Tables:
  Globals:
Exports:
  Functions:
    "malloc": [I32] -> [I32]
    "free": [I32] -> []
    "calloc": [I32, I32] -> [I32]
    "realloc": [I32, I32] -> [I32]
    "_start": [] -> []
    "hello": [] -> []
    "asyncify_start_unwind": [I32] -> []
    "asyncify_stop_unwind": [] -> []
    "asyncify_start_rewind": [I32] -> []
    "asyncify_stop_rewind": [] -> []
    "asyncify_get_state": [] -> [I32]
  Memories:
    "memory": not shared (2 pages..)
  Tables:
  Globals:
```

The same program targeting WASI via Go (actually [`gotip`](https://pkg.go.dev/golang.org/dl/gotip)) (`GOOS=wasip1 GOARCH=wasm gotip build -o go.wasm`) produces a module with the following signature.

```
Type: wasm
Size: 1.4 MB
Imports:
  Functions:
    "wasi_snapshot_preview1"."sched_yield": [] -> [I32]
    "wasi_snapshot_preview1"."proc_exit": [I32] -> []
    "wasi_snapshot_preview1"."args_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."args_sizes_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."clock_time_get": [I32, I64, I32] -> [I32]
    "wasi_snapshot_preview1"."environ_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."environ_sizes_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."random_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."poll_oneoff": [I32, I32, I32, I32] -> [I32]
  Memories:
  Tables:
  Globals:
Exports:
  Functions:
    "_start": [] -> []
  Memories:
    "memory": not shared (266 pages..)
  Tables:
  Globals:
```

Godot Wasm provides default implementations for the following small subset of WASI import functions according to the [WASI spec](https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md).
- `wasi_snapshot_preview1.clock_time_get`
- `wasi_snapshot_preview1.args_sizes_get`
- `wasi_snapshot_preview1.args_get`
- `wasi_snapshot_preview1.environ_sizes_get` (stubbed out)
- `wasi_snapshot_preview1.environ_get` (stubbed out)
- `wasi_snapshot_preview1.random_get`
- `wasi_snapshot_preview1.args_sizes_get`
- `wasi_snapshot_preview1.args_get`
- `wasi_snapshot_preview1.environ_sizes_get`
- `wasi_snapshot_preview1.environ_get`
- `wasi_snapshot_preview1.random_get`
- `wasi_snapshot_preview1.clock_time_get`

With the background info out of the way, there are a few options to enable/ease support Golang.
1. Extend default WASI support. At the very least, `wasi_snapshot_preview1.sched_yield` and `wasi_snapshot_preview1.poll_oneoff` would need to be provided by default. If you can provide the signature (e.g. `wasmer inspect go.wasm`) of modules you've compiled from Go, perhaps we can find other required functions.
2. Implement required function in GDScript. This can be done immediately to enable support for modules with unmet WASI requirements. Import functions can be provided in a dictionary of the shape `{ "functions": { "wasi_snapshot_preview1.sched_yield": [self, "sched_yield"] } }`. One of the major disadvantages to this approach would be a massive decrease in speed compared to a native implementation if the import function is called with any frequency.
3. Godot Wasm forwards the runtime's default WASI implementation to the module. I'm not entirely sure what this would look like without a little more research. One downside to this approach would be the assumptions made about the Wasm runtime used. Currently, the only assumption/requirement is that the runtime abides by the [Wasm C API](https://github.com/WebAssembly/wasm-c-api) which makes porting support very simple.

As for Wazero support, it seems as though this runtime uses a bespoke API. Supporting Wazero would be quite an undertaking. Rather, it may make sense to petition for Wazero to adopt the Wasm C API as this is as close as we've got to a universally adopted Wasm runtime API standard.
